// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: queue.proto
#ifndef GRPC_queue_2eproto__INCLUDED
#define GRPC_queue_2eproto__INCLUDED

#include "queue.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace TicketSystem {

class Office final {
 public:
  static constexpr char const* service_full_name() {
    return "TicketSystem.Office";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::TicketSystem::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TicketSystem::Response>> AsyncReserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TicketSystem::Response>>(AsyncReserveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TicketSystem::Response>> PrepareAsyncReserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TicketSystem::Response>>(PrepareAsyncReserveRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TicketSystem::Response>* AsyncReserveRaw(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TicketSystem::Response>* PrepareAsyncReserveRaw(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::TicketSystem::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>> AsyncReserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>>(AsyncReserveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>> PrepareAsyncReserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>>(PrepareAsyncReserveRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response, std::function<void(::grpc::Status)>) override;
      void Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>* AsyncReserveRaw(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>* PrepareAsyncReserveRaw(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Reserve_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Reserve(::grpc::ServerContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Reserve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Reserve() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Reserve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reserve(::grpc::ServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReserve(::grpc::ServerContext* context, ::TicketSystem::Request* request, ::grpc::ServerAsyncResponseWriter< ::TicketSystem::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Reserve<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Reserve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Reserve() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::TicketSystem::Request, ::TicketSystem::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response) { return this->Reserve(context, request, response); }));}
    void SetMessageAllocatorFor_Reserve(
        ::grpc::MessageAllocator< ::TicketSystem::Request, ::TicketSystem::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TicketSystem::Request, ::TicketSystem::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Reserve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reserve(::grpc::ServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reserve(
      ::grpc::CallbackServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Reserve<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Reserve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Reserve() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Reserve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reserve(::grpc::ServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Reserve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Reserve() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Reserve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reserve(::grpc::ServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReserve(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Reserve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Reserve() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Reserve(context, request, response); }));
    }
    ~WithRawCallbackMethod_Reserve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reserve(::grpc::ServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reserve(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Reserve : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Reserve() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TicketSystem::Request, ::TicketSystem::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TicketSystem::Request, ::TicketSystem::Response>* streamer) {
                       return this->StreamedReserve(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Reserve() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Reserve(::grpc::ServerContext* /*context*/, const ::TicketSystem::Request* /*request*/, ::TicketSystem::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReserve(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TicketSystem::Request,::TicketSystem::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Reserve<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Reserve<Service > StreamedService;
};

}  // namespace TicketSystem


#endif  // GRPC_queue_2eproto__INCLUDED
