// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: queue.proto

#include "queue.pb.h"
#include "queue.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace TicketSystem {

static const char* Office_method_names[] = {
  "/TicketSystem.Office/Reserve",
};

std::unique_ptr< Office::Stub> Office::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Office::Stub> stub(new Office::Stub(channel, options));
  return stub;
}

Office::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Reserve_(Office_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Office::Stub::Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::TicketSystem::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TicketSystem::Request, ::TicketSystem::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Reserve_, context, request, response);
}

void Office::Stub::async::Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TicketSystem::Request, ::TicketSystem::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reserve_, context, request, response, std::move(f));
}

void Office::Stub::async::Reserve(::grpc::ClientContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reserve_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>* Office::Stub::PrepareAsyncReserveRaw(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TicketSystem::Response, ::TicketSystem::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Reserve_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TicketSystem::Response>* Office::Stub::AsyncReserveRaw(::grpc::ClientContext* context, const ::TicketSystem::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReserveRaw(context, request, cq);
  result->StartCall();
  return result;
}

Office::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Office_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Office::Service, ::TicketSystem::Request, ::TicketSystem::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Office::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TicketSystem::Request* req,
             ::TicketSystem::Response* resp) {
               return service->Reserve(ctx, req, resp);
             }, this)));
}

Office::Service::~Service() {
}

::grpc::Status Office::Service::Reserve(::grpc::ServerContext* context, const ::TicketSystem::Request* request, ::TicketSystem::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TicketSystem

